project_id = "fdljfwseyawrcgcloysn"

[functions.send-reminder-notifications]
verify_jwt = false

[functions.register-push-token]
verify_jwt = true

[functions.get-onesignal-config]
verify_jwt = false
